### ISSUE TITLE
Access to AllowAutoRedirect in HttpClientHandler.AllowAutoRedirect

### ISSUE THREAD

**Issue by MAliM1988** [DalSoft/DalSoft.RestClient#101] opened 2020-09-08 12:55 UTC
Hi everyone

in my company we are use dalsoft rest client for implementation external rest api service wrapper,on new project external api have a Post method with own model and headers after calling result of method redirect with http status 302 and location result in the header.

When we implement this method with dalsoft rest client we get bad request with http status code 400 but when we test with postman this method work and redirect to location result,in my search i have found HttpClientHandler.AllowAutoRedirect for handling  automatically follow HTTP redirection headers to the new location of the resource with http client how can i access to this prop in dalsoft rest client?

**Comment by DalSoft** [comment] 2020-09-11 08:39
Sure by design everything you can do with HttpClient can be done with DalSoft.RestClient.

Example:

```cs
var httpClientHandler = new HttpClientHandler { AllowAutoRedirect = true };
var restClient = new RestClient("https://myapi.com", new Config(httpClientHandler));
```

More info https://restclient.dalsoft.io/docs/httpclienthandler/

**Comment by DalSoft** [comment] 2020-09-24 12:47
Closing if this didn't solve your problem please re-open

**Closed by DalSoft** 2020-09-24 12:47 UTC
