### ISSUE TITLE
The equivalent VB.net code of the example?

### ISSUE THREAD

**Issue by Altiano** [DalSoft/DalSoft.RestClient#50] opened 2018-05-25 04:24 UTC
This exmple:

```
dynamic client = new RestClient("http://jsonplaceholder.typicode.com");
await client.Users(1).Get();
```

What I try:

```
Dim client As Object = New RestClient("http://jsonplaceholder.typicode.com")
Await client.Users(1).Get()
```

Get this error:
`System.InvalidCastException: 'Conversion from type 'MemberAccessWrapper' to type 'Boolean' is not valid.'`

**Comment by DalSoft** [comment] 2018-05-25 11:08
I haven't done VB.NET for a bit could you try:

`Dim client As dynamic = New RestClient("http://jsonplaceholder.typicode.com")
Await client.Users(1).Get()`

The reason I think you are getting the problem is because it needs to be a dynamic type (not an object) to invoke the dynamic methods.

Let me know if this works, if it doesn't I'll create my own VB.NET project myself and see what's going on.

**Comment by Altiano** [comment] 2018-05-29 05:56
I believe there is no `dynamic` class in .net.
I've try it.

**Comment by DalSoft** [comment] 2018-05-30 01:01
This works 
https://dotnetfiddle.net/cykKSZ

I did trigger that error though, so it might be the package version for example for .NET 4.5 I had to downgrade to 2.4.0.

I'll update the documentation to reflect package version to framework.

**Comment by Altiano** [comment] 2018-05-30 12:13
Something's probably wrong with my setup.
I still can't run the program.
With that example, this time it not produce error but it also not produce any data.

I'm using Net Framework 4.7.1, 
with compiler options: explicit (on), strict (off), compare (binary), infer (on).

I think some assembly not correctly referenced on this version of .Net
<img width="195" alt="1" src="https://user-images.githubusercontent.com/8316282/40719321-df8371e2-6445-11e8-9c01-668cb4cb3db8.png">

**Comment by DalSoft** [comment] 2018-07-02 23:08
Closing as no further contact, feel free to re-open at anytime, or speak to me on gitter.

**Closed by DalSoft** 2018-07-02 23:08 UTC
